name: Check Build

on:
  pull_request:
    branches:
      - main

jobs:
    build:
        runs-on: ${{matrix.os}}
        strategy: 
          matrix:
            os: [ubuntu-latest]
            node-version: [18,22,23]

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Node.js ${{matrix.node-version}}
              uses: actions/setup-node@v4
              with:
                node-version: ${{matrix.node-version}}

            - name: Install dependencies
              run: npm install

            - name: Correr Lint
              run: npm run lint

            - name: Correr los test 
              run: npm run test

            - name: Build
              run: npm run build